version: '3'
services:
  db:
    image: mongo:latest
    volumes:
      - "dbdata:/var/lib/mongodb/data"
      - "./db/seeds.js:/docker-entrypoint-initdb.d/seeds.js:ro"
    environment: 
      # - MONGO_INITDB_ROOT_USERNAME=futureproof
      - MONGO_INITDB_DATABASE=studyJWT
      # - MONGO_INITDB_ROOT_PASSWORD=pass
  server:
    image: node:12.18.4
    working_dir: /code
    ports: 
      - 3000:3000
    environment: 
      - DB_NAME=studyJWT
      - DB_CONNECT=mongodb://db:27017
    # env_file:
    #   - ./api/.env  
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm start"    
volumes:
  dbdata: